In [9]:
import pandas as pd
import numpy as np

In [10]:
data = pd.read_csv(r"C:\Users\91972\Downloads\kc_house_data.csv")

In [11]:
df = data.copy()
# df.info()
df.sample(2)
df['date'] = pd.to_datetime(df['date'])
df.sample()
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21613 entries, 0 to 21612
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   id             21613 non-null  int64
 1   date           21613 non-null  datetime64[ns]
 2   price          21613 non-null  float64
 3   bedrooms       21613 non-null  int64
 4   bathrooms      21613 non-null  float64
 5   sqft_living    21613 non-null  int64
 6   sqft_lot       21613 non-null  int64
 7   floors         21613 non-null  float64
 8   waterfront     21613 non-null  int64
 9   view           21613 non-null  int64
 10  condition      21613 non-null  int64
 11  grade          21613 non-null  int64
 12  sqft_above     21613 non-null  int64
 13  sqft_basement  21613 non-null  int64
 14  yr_built       21613 non-null  int64
 15  yr_renovated   21613 non-null  int64
 16  zipcode        21613 non-null  int64
 17  lat            21613 non-null  float64
 18  long           21613 non-null  float64
 19  sqft_living15  21613 non-null  int64
 20  sqft_lot15     21613 non-null  int64
dtypes: datetime64[ns](1), float64(5), int64(15)
memory usage: 3.5 MB

In [12]:
# print(df.sample(50).to_string())

# df.drop('id',axis=1,inplace=True)

df2 = df.set_index(df['date'])      #Index = Date


df3 = df.drop('date',axis=1)
df3[['waterfront','view']]
df3=df3.drop(['waterfront','view'],axis=1)
df3.query('bedrooms == 3 and bathrooms == 1  and floors==1	and condition ==3 and ( yr_built < 1901 or yr_built > 1985 )')    # By query we found yr_built has influence on price
df3 = df3.drop(['zipcode','lat','long'],axis=1)
df3.columns
df3.drop('price',axis=1).corr()

,id,bedrooms,bathrooms,sqft_living,sqft_lot,floors,condition,grade,sqft_above,sqft_basement,yr_built,yr_renovated,sqft_living15,sqft_lot15
id,1.000000,0.001286,0.005160,-0.012258,-0.132109,0.018525,-0.023783,0.008130,-0.010842,-0.005151,0.021380,-0.016907,-0.002901,-0.138798
bedrooms,0.001286,1.000000,0.515884,0.576671,0.031703,0.175429,0.028472,0.356967,0.477600,0.303093,0.154178,0.018841,0.391638,0.029244
bathrooms,0.005160,0.515884,1.000000,0.754665,0.087740,0.500653,-0.124982,0.664983,0.685342,0.283770,0.506019,0.050739,0.568634,0.087175
sqft_living,-0.012258,0.576671,0.754665,1.000000,0.172826,0.353949,-0.058753,0.762704,0.876597,0.435043,0.318049,0.055363,0.756420,0.183286
sqft_lot,-0.132109,0.031703,0.087740,0.172826,1.000000,-0.005201,-0.008958,0.113621,0.183512,0.015286,0.053080,0.007644,0.144608,0.718557
floors,0.018525,0.175429,0.500653,0.353949,-0.005201,1.000000,-0.263768,0.458183,0.523885,-0.245705,0.489319,0.006338,0.279885,-0.011269
condition,-0.023783,0.028472,-0.124982,-0.058753,-0.008958,-0.263768,1.000000,-0.144674,-0.158214,0.174105,-0.361417,-0.060618,-0.092824,-0.003406
grade,0.008130,0.356967,0.664983,0.762704,0.113621,0.458183,-0.144674,1.000000,0.755923,0.168392,0.446963,0.014414,0.713202,0.119248
sqft_above,-0.010842,0.477600,0.685342,0.876597,0.183512,0.523885,-0.158214,0.755923,1.000000,-0.051943,0.423898,0.023285,0.731870,0.194050
sqft_basement,-0.005151,0.303093,0.283770,0.435043,0.015286,-0.245705,0.174105,0.168392,-0.051943,1.000000,-0.133124,0.071323,0.200355,0.017276
yr_built,0.021380,0.154178,0.506019,0.318049,0.053080,0.489319,-0.361417,0.446963,0.423898,-0.133124,1.000000,-0.224874,0.326229,0.070958
yr_renovated,-0.016907,0.018841,0.050739,0.055363,0.007644,0.006338,-0.060618,0.014414,0.023285,0.071323,-0.224874,1.000000,-0.002673,0.007854
sqft_living15,-0.002901,0.391638,0.568634,0.756420,0.144608,0.279885,-0.092824,0.713202,0.731870,0.200355,0.326229,-0.002673,1.000000,0.183192
sqft_lot15,-0.138798,0.029244,0.087175,0.183286,0.718557,-0.011269,-0.003406,0.119248,0.194050,0.017276,0.070958,0.007854,0.183192,1.000000

In [13]:
import seaborn as sns 
import matplotlib.pyplot as plt 

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(df3.drop('price',axis=1),df3.loc[:,['price']],test_size=0.2,random_state=89)

# from sklearn.preprocessing import P

In [14]:
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler , PolynomialFeatures
from sklearn.linear_model import LinearRegression , SGDRegressor,Ridge,Lasso , ElasticNet

In [15]:
sd = StandardScaler()
lr = LinearRegression()

In [16]:
# Pipeline 1 for LR fitting

pipe1 = Pipeline(steps = [('Standardized',sd),
                          ('Model',lr)])

pipe1.fit(X_train,y_train)
y_trained1 = pipe1.predict(X_train)
y_pred1 = pipe1.predict(X_test)

from sklearn.metrics import r2_score
print(f"R2_Score on training data is {r2_score(y_train,y_trained1)*100}\nR2_Score on test data is {r2_score(y_test,y_pred1)*100}  ")

R2_Score on training data is 62.413277816331956
R2_Score on test data is 59.988280229540116

In [26]:
# Pipeline 2 for LR fitting using Ridge
for i in range(5):
    pipe2 = Pipeline(steps = [('Standardized',sd),
                            ('Model',Ridge(alpha=i))])

    pipe2.fit(X_train,y_train)
    y_trained2 = pipe2.predict(X_train)
    y_pred2 = pipe2.predict(X_test)

    from sklearn.metrics import r2_score
    print(f"R2_Score on training data is {r2_score(y_train,y_trained2)*100}\nR2_Score on test data is {r2_score(y_test,y_pred2)*100}  ")

R2_Score on training data is 62.4056186160477
R2_Score on test data is 60.2316965537582
R2_Score on training data is 62.41327759077887
R2_Score on test data is 59.98918182298745
R2_Score on training data is 62.41327691439984
R2_Score on test data is 59.9900826153053
R2_Score on training data is 62.41327578761482
R2_Score on test data is 59.99098260712136
R2_Score on training data is 62.413274210843305
R2_Score on test data is 59.991881799062654

In [27]:
# Pipeline 3 for LR fitting using Lasso
for i in range(100,500,50):
    pipe3 = Pipeline(steps = [('Standardized',sd),
                            ('Model',Lasso(alpha=i,max_iter=10000))])

    pipe3.fit(X_train,y_train)
    y_trained3 = pipe3.predict(X_train)
    y_pred3 = pipe3.predict(X_test)

    from sklearn.metrics import r2_score
    print(f"R2_Score on training data is {r2_score(y_train,y_trained3)*100}\nR2_Score on test data is {r2_score(y_test,y_pred3)*100}  ")

R2_Score on training data is 62.413168963185164
R2_Score on test data is 60.00345573410387
R2_Score on training data is 62.413033133634265
R2_Score on test data is 60.01087807041087
R2_Score on training data is 62.41284250013693
R2_Score on test data is 60.01831575946927
R2_Score on training data is 62.41259900214131
R2_Score on test data is 60.025450299743625
R2_Score on training data is 62.41229999797303
R2_Score on test data is 60.03269695039091
R2_Score on training data is 62.41194701713715
R2_Score on test data is 60.03982580944618
R2_Score on training data is 62.41154084835428
R2_Score on test data is 60.046785695244374
R2_Score on training data is 62.411078472024364
R2_Score on test data is 60.053837512379445

In [28]:
# Pipeline 4 for LR fitting using ElasticNet

pipe4 = Pipeline(steps = [('Standardized',sd),
                        ('Model',ElasticNet(alpha=1,l1_ratio=0.95))])

pipe4.fit(X_train,y_train)
y_trained4 = pipe4.predict(X_train)
y_pred4 = pipe4.predict(X_test)

from sklearn.metrics import r2_score
print(f"R2_Score on training data is {r2_score(y_train,y_trained4)*100}\nR2_Score on test data is {r2_score(y_test,y_pred4)*100}  ")

R2_Score on training data is 62.28101285985299
R2_Score on test data is 60.523940653405184

In [29]:
# Pipeline 5 for Polynomial Fitting
pipe5 = Pipeline(steps = [('Poly',PolynomialFeatures(degree=2)),
                          ('Standardized',sd),
                          ('Model',lr)])



pipe5.fit(X_train,y_train)
y_trained5 = pipe5.predict(X_train)
y_pred5 = pipe5.predict(X_test)

from sklearn.metrics import r2_score
print(f"R2_Score on training data is {r2_score(y_train,y_trained5)*100}\nR2_Score on test data is {r2_score(y_test,y_pred5)*100}  ")

R2_Score on training data is 72.82162268146635
R2_Score on test data is 63.62523576053775

In [30]:
# Pipeline 6 for Polynomial Fitting using ElasticNet
pipe6 = Pipeline(steps = [('Poly',PolynomialFeatures(degree=2,include_bias=False)),
                          ('Standardized',sd),
                          ('Model',ElasticNet(alpha=1,l1_ratio=0.9,max_iter=10000))])



pipe6.fit(X_train,y_train)
y_trained6 = pipe6.predict(X_train)
y_pred6 = pipe6.predict(X_test)

from sklearn.metrics import r2_score
print(f"R2_Score on training data is {r2_score(y_train,y_trained6)*100}\nR2_Score on test data is {r2_score(y_test,y_pred6)*100}  ")

R2_Score on training data is 69.8087362158835
R2_Score on test data is 64.90642945622862

In [24]:
from sklearn.decomposition import PCA
for j in (range(1,15)):
    pca = PCA(n_components=j)
    X_traina = X_train.copy()
    X_traineeed = pca.fit_transform(X_traina)
    print(f'{j}____{pca.explained_variance_ratio_.sum()}')

# only 7 PC is needed

1____0.9999999996932246
2____0.999999999963124
3____0.9999999999997237
4____0.9999999999999284
5____0.9999999999999618
6____0.9999999999999821
7____0.9999999999999999
8____0.9999999999999999
9____0.9999999999999999
10____0.9999999999999999
11____0.9999999999999999
12____0.9999999999999999
13____0.9999999999999999
14____0.9999999999999999

In [47]:
# Pipeline 6 for Polynomial Fitting using ElasticNet
from sklearn.preprocessing import PowerTransformer

pipe7 = Pipeline(steps = [
                          ('Standardized',sd),
                          ('PT',PowerTransformer()),
                          ('PCA',pca),
                          ('Poly',PolynomialFeatures(degree=2,include_bias=False)),
                          ('Model',LinearRegression())
                          ])



pipe7.fit(X_train,y_train)
y_trained7 = pipe7.predict(X_train)
y_pred7 = pipe7.predict(X_test)

from sklearn.metrics import r2_score
print(f"R2_Score on training data is {r2_score(y_train,y_trained7)*100}\nR2_Score on test data is {r2_score(y_test,y_pred7)*100}  ")

R2_Score on training data is 70.40802650255077
R2_Score on test data is 65.61491662922168

In [110]:
y_trained = [y_trained1,y_trained2,y_trained3,y_trained4,y_trained5,y_trained6,y_trained7]
y_predicted = [y_pred1,y_pred2,y_pred3,y_pred4,y_pred5,y_pred6,y_pred7]

from  sklearn.metrics import mean_absolute_error , mean_squared_error

# for i in range(7):
    # print(f"BY MODEL {i+1}\nR2_Score on training data is {r2_score(y_train,y_trained[i])*100}\nR2_Score on test data is {r2_score(y_test,y_predicted[i])*100}\n ")
R2_train = [0,1,2,3,4,5,6]
R2_test = [0,1,2,3,4,5,6]
mae_train = [0,1,2,3,4,5,6]
mae_test = [0,1,2,3,4,5,6]
rmse_train = [0,1,2,3,4,5,6]
rmse_test = [0,1,2,3,4,5,6]
for i in range(7):
    R2_train[i] = r2_score(y_train,y_trained[i])*100
    R2_test[i] = r2_score(y_test,y_predicted[i])*100
    mae_train[i] = mean_absolute_error(y_train,y_trained[i])*100
    mae_test[i] = mean_absolute_error(y_test,y_predicted[i])*100
    rmse_train[i] = np.sqrt(mean_squared_error(y_train,y_trained[i]))*100
    rmse_test[i] = np.sqrt(mean_squared_error(y_test,y_predicted[i]))*100

Model_test = pd.DataFrame({
                          'Model' : ['LR','LR + Ridge','LR + Lasso','LR + ElasticNet','Polynomial + LR','Polynomial + ElasticNet' , 'Polynomial + PCA + LR'],
                          ('Training','R2'):np.round(R2_train,2),
                          ('Training','MAE'):np.round(mae_train,2),
                          ('Training','RMSE'):np.round(rmse_train,2),
                          ('Test','R2'):np.round(R2_test,2),
                          ('Test','MAE'):np.round(mae_test,2),
                          ('Test','RMSe'):np.round(rmse_test,2)
                          })
Model_test

,Model,"(Training, R2)","(Training, MAE)","(Training, RMSE)","(Test, R2)","(Test, MAE)","(Test, RMSe)"
0,LR,62.41,14580657.44,22936777.44,59.99,14504042.14,21357838.16
1,LR + Ridge,62.41,14579802.47,22936778.54,59.99,14502928.46,21356876.90
2,LR + Lasso,62.41,14561666.01,22937448.49,60.05,14482536.60,21340334.09
3,LR + ElasticNet,62.28,14447460.46,22977098.43,60.52,14329659.92,21214391.47
4,Polynomial + LR,72.82,12690700.89,19504145.83,63.63,12909623.79,20364032.23
5,Polynomial + ElasticNet,69.81,13171527.15,20556814.64,64.91,13206477.26,20002185.96
6,Polynomial + PCA + LR,70.41,12986655.88,20351767.77,65.61,13149678.17,19799249.25

In [113]:
print(f"On observing the dataframe Model_test we found that the most suitable model among these is:\n Polynomial + PCA + LR with corresponding accuracy score\n{Model_test.iloc[6,:]}")

On observing the dataframe Model_test we found that the most suitable model among these is:
 Polynomial + PCA + LR with corresponding accuracy score
Model               Polynomial + PCA + LR
(Training, R2)                      70.41
(Training, MAE)               12986655.88
(Training, RMSE)              20351767.77
(Test, R2)                          65.61
(Test, MAE)                   13149678.17
(Test, RMSe)                  19799249.25
Name: 6, dtype: object